### PR TITLE
feat: add general notification for conversation history export

### PR DESCRIPTION
**Pull request by sianw**
A new feature is being added to the Employee App which allows employees to export a file of conversation history records. A notification must be added to inform the employee when the file is ready to be downloaded (similar to the Audit export).

Tested on beck environment by generating & pushing own docker image, notifications working as expected.

### CODE REVIEW

**Comment by eacarvalho** [comment]
Please @ajitavbb and @amorimluzia can you review this pull request? Btw @sianw there is a doc folder which describers the GN in this repository?

Last question, this notification should be part of ModelBank as well?

**Comment by sianw** [comment]
@eacarvalho Thanks, I've updated the docs with the new general notification. It will need to be on ModelBank too, I'm just working on the PR for that now - will be raised shortly.

**Review by joshuad-bb — APPROVED** [review]

**Comment by sianw** [comment]
@amorimluzia We're planning to release the changes in an intermediate release of the BB bom, likely tomorrow. I understand that this is required prior to deployment on ModelBank however as this is our first contribution to engagements we wanted to get the PRs up early.

**Review by ajitavbb — APPROVED** [review]

**Review by amorimluzia — APPROVED** [review]

**Comment by sianw** [comment]
Feature release has been postponed - closing the PR and will be reopened when feature is released externally.

**Pull request closed without merging**
